package main

import (
	"bytes"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestValidateManifest(t *testing.T) {
	manifest := fixtureManifest(t)
	if err := validateManifest(manifest, "v0.6.0"); err != nil {
		t.Fatalf("valid manifest rejected: %v", err)
	}

	tests := []struct {
		name   string
		mutate func(*releaseManifest)
		want   string
	}{
		{
			name: "wrong repository",
			mutate: func(manifest *releaseManifest) {
				manifest.Source.Repository = "example/guardrails"
			},
			want: "unexpected source repository",
		},
		{
			name: "missing target",
			mutate: func(manifest *releaseManifest) {
				delete(manifest.Artifacts, "x86_64-unknown-linux-gnu")
			},
			want: "missing artifact",
		},
		{
			name: "invalid digest",
			mutate: func(manifest *releaseManifest) {
				artifact := manifest.Artifacts["aarch64-apple-darwin"]
				artifact.Archive.SHA256 = "not-a-digest"
				manifest.Artifacts["aarch64-apple-darwin"] = artifact
			},
			want: "invalid archive digest",
		},
		{
			name: "missing source",
			mutate: func(manifest *releaseManifest) {
				manifest.Source = nil
			},
			want: "source is required",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			manifest := fixtureManifest(t)
			test.mutate(manifest)
			err := validateManifest(manifest, "v0.6.0")
			if err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("validateManifest() error = %v, want %q", err, test.want)
			}
		})
	}
}

func TestValidateManifestAllowsLegacyReleaseWithoutSource(t *testing.T) {
	manifest := fixtureManifest(t)
	manifest.Version = legacyVersion
	manifest.Source = nil
	if err := validateManifest(manifest, legacyVersion); err != nil {
		t.Fatalf("legacy manifest rejected: %v", err)
	}
}

func TestGenerateSource(t *testing.T) {
	manifest := fixtureManifest(t)
	generated, err := generateSource(manifest)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "guardrails_artifacts.go", generated, parser.AllErrors); err != nil {
		t.Fatalf("generated invalid Go: %v", err)
	}
	for _, expected := range []string{
		"Code generated by go run ./internal/tools/updateguardrails",
		`const guardrailsPinnedVersion = "v0.6.0"`,
		manifest.Artifacts["aarch64-apple-darwin"].Archive.SHA256,
	} {
		if !bytes.Contains(generated, []byte(expected)) {
			t.Errorf("generated source missing %q", expected)
		}
	}
	again, err := generateSource(manifest)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(generated, again) {
		t.Fatal("generation is not deterministic")
	}
}

func TestReadManifestRejectsUnknownFields(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("testdata", "guardrails-release.json"))
	if err != nil {
		t.Fatal(err)
	}
	data = bytes.Replace(data, []byte(`"schema_version": 1`), []byte(`"schema_version": 1, "unexpected": true`), 1)
	path := filepath.Join(t.TempDir(), "manifest.json")
	if err := os.WriteFile(path, data, 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := readManifest(path); err == nil || !strings.Contains(err.Error(), "unknown field") {
		t.Fatalf("readManifest() error = %v, want unknown field", err)
	}
}

func fixtureManifest(t *testing.T) *releaseManifest {
	t.Helper()
	manifest, err := readManifest(filepath.Join("testdata", "guardrails-release.json"))
	if err != nil {
		t.Fatal(err)
	}
	return manifest
}
