version: 2

builds:
  - main: ./cmd/konvu
    binary: konvu
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "konvu-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  github:
    owner: KonvuInc
    name: konvu-cli
