package cmd

import (
	"github.com/spf13/cobra"
)

var (
	guardrailsShowAPIKey string
	guardrailsShowModel  string
)

var guardrailsShowCmd = &cobra.Command{
	Use:   "show [file[:line]] [profile-dir]",
	Short: "Show the profile for a file or the whole repo",
	Long: `Show the profile generated by 'konvu guardrails scan'.

Reads .konvu/guardrails/ under the current directory unless a profile-dir is
given.

Thin wrapper over the cached guardrails-cli binary -- see 'konvu guardrails
scan --help' for the shared bootstrap behavior.`,
	Args: cobra.ArbitraryArgs,
	Run: func(cmd *cobra.Command, args []string) {
		runGuardrailsReadOnly(append([]string{"show"}, args...))
	},
}

func init() {
	guardrailsShowCmd.Flags().StringVar(&guardrailsShowAPIKey, "openai-api-key", "", "OpenAI API key (prefer OPENAI_API_KEY to avoid shell history)")
	guardrailsShowCmd.Flags().StringVar(&guardrailsShowModel, "openai-model", "gpt-4o", "OpenAI model used with --openai-api-key")
	guardrailsCmd.AddCommand(guardrailsShowCmd)
}
