// Code generated by go run ./internal/tools/updateguardrails; DO NOT EDIT.

package cmd

// guardrailsPinnedVersion is the Guardrails release installed by this version
// of Konvu CLI.
const guardrailsPinnedVersion = "v0.5.2"

type guardrailsArtifact struct {
	archiveSHA256         string
	mainSHA256            string
	resourceScannerSHA256 string
}

// guardrailsArtifacts is the trust anchor for downloaded runtime bytes.
var guardrailsArtifacts = map[string]guardrailsArtifact{
	"aarch64-apple-darwin": {
		archiveSHA256:         "490186d3deccaeb937007c83a0e1d6c98f74cc7f354725898cbd2e9c07318eaf",
		mainSHA256:            "9568e10a69bd145e6db7851aa1cb65358ef0485bcb81c657efeaaa3e6a5be290",
		resourceScannerSHA256: "a59adc52d86b3c38fb503c9f2a6049998e467749ac43430d919044d2097f7250",
	},
	"x86_64-apple-darwin": {
		archiveSHA256:         "dba2a40e3263825cab8b0c17cdcde1f8eade4a9117e32731246e92434a6a8760",
		mainSHA256:            "100f019f9b46daa0888be8dd5da033677dd264c9aaa6750370aa6110c5fdec00",
		resourceScannerSHA256: "02b900d8956b96b8fe9cea5e4198fbaf3d8e1d465d7ad7f795e06bede488b75e",
	},
	"aarch64-unknown-linux-gnu": {
		archiveSHA256:         "db6a5b067e55cf5bc983cf8a44bafdab2637b6c73cb05f3ceff9c18f65cbeea1",
		mainSHA256:            "3de139373db9012cbbaeebeea156437c25c4a1b9805ce222c6e1b2b9d28a1122",
		resourceScannerSHA256: "78e8be3908512e2ebcfecd85f2998b2114f08350074b9dba8e84452f1be89863",
	},
	"x86_64-unknown-linux-gnu": {
		archiveSHA256:         "7c4dbd0e78f949e05d7994097693e93b4298b8bf0ec7b12b7be5100c869966a5",
		mainSHA256:            "4fdd890578dec7503f500216d7c9aa675f1dc4564cca91404e7ff6fe87db2324",
		resourceScannerSHA256: "b572cd4d5ce399957419dcf6198752c7c36219005e1dca7d7f4ae165b6de4bab",
	},
}
