// Code generated by go run ./internal/tools/updateguardrails; DO NOT EDIT.

package cmd

// guardrailsPinnedVersion is the Guardrails release installed by this version
// of Konvu CLI.
const guardrailsPinnedVersion = "v0.6.0"

type guardrailsArtifact struct {
	archiveSHA256         string
	mainSHA256            string
	resourceScannerSHA256 string
}

// guardrailsArtifacts is the trust anchor for downloaded runtime bytes.
var guardrailsArtifacts = map[string]guardrailsArtifact{
	"aarch64-apple-darwin": {
		archiveSHA256:         "0626fa8b0c8fa71388e3287e7b4dbca3e35c956060e72e0f90312a704bd5d59f",
		mainSHA256:            "e3c783ae47dacb020645acdd874f0b11023504033472981ebd1efe151e7bf01b",
		resourceScannerSHA256: "04fedd15e753ce6f9aa7b06bb3fd8fdb78dca547205a44627f8ec32307c3e100",
	},
	"x86_64-apple-darwin": {
		archiveSHA256:         "85c3874b8bd5ec118cf9ff4293875b6f405ed549e36f46a5e75c47cc659838bb",
		mainSHA256:            "1e866d055a4ff2f1b0ba1b3f6e31e66926fb7722fec13de2367b8f7957e79a78",
		resourceScannerSHA256: "783e896951a9b8f40bb80045bbabcf4ec09182f22b2ee9333b03ebbe80aa1a62",
	},
	"aarch64-unknown-linux-gnu": {
		archiveSHA256:         "db17d02edd806a637266e144480fb3d48b4ac96c4fdc870a35ad34330b8c8086",
		mainSHA256:            "58db069f63f2eebcc903265ab1d792252e3ad0b122ff76696a39a39f78ba62fa",
		resourceScannerSHA256: "66439b158bdbfadf0ad4d997743bb43cd58da50762cea14edaffd472464b1f1b",
	},
	"x86_64-unknown-linux-gnu": {
		archiveSHA256:         "33482adf552026d683343348bd5403c200991576f5eefaa163095c15538fdcdf",
		mainSHA256:            "e435554e7382f3dcf828c3bf0925116534dfef5a8a5dbcbe337487fe1eb157c9",
		resourceScannerSHA256: "0a13f59646bef37bd27c2e45f96c8e92a708658b6e053c5e46dd79cc3c9460ae",
	},
}
