package cmd

import (
	"github.com/spf13/cobra"
)

var guardrailsShowCmd = &cobra.Command{
	Use:   "show [file[:line]] [profile-dir]",
	Short: "Show the profile for a file or the whole repo",
	Long: `Show the profile generated by 'konvu guardrails scan'.

Reads .konvu/guardrails/ under the current directory unless a profile-dir is
given.

Thin wrapper over the cached guardrails-cli binary -- see 'konvu guardrails
scan --help' for the shared bootstrap behavior.`,
	Args: cobra.ArbitraryArgs,
	Run: func(cmd *cobra.Command, args []string) {
		runGuardrailsReadOnly(append([]string{"show"}, args...))
	},
}

func init() {
	guardrailsCmd.AddCommand(guardrailsShowCmd)
}
