// Code generated by go run ./internal/tools/updateguardrails; DO NOT EDIT.

package cmd

// guardrailsPinnedVersion is the Guardrails release installed by this version
// of Konvu CLI.
const guardrailsPinnedVersion = "v0.6.10"

type guardrailsArtifact struct {
	archiveSHA256         string
	mainSHA256            string
	resourceScannerSHA256 string
}

// guardrailsArtifacts is the trust anchor for downloaded runtime bytes.
var guardrailsArtifacts = map[string]guardrailsArtifact{
	"aarch64-apple-darwin": {
		archiveSHA256:         "560a08b9fc46f80c197eb5023942a3d70da4f12a780a6877d740b471bebe63ab",
		mainSHA256:            "b1ec496d6b23899b1cef24cc4ac076a15616d1b7dff669b7eb6d390b92ffdd38",
		resourceScannerSHA256: "b85e7771eba712fcc0e70ced6e82fa047c38604481edbc1077cfb7e48aca09dd",
	},
	"x86_64-apple-darwin": {
		archiveSHA256:         "a2b620250d2eb243a4e14e2b5ec7f54c806c454900cbb057095353da2507feb2",
		mainSHA256:            "81e5584ae76780c52063f175d7038291a7416222a4e681a8943046593bebc7bf",
		resourceScannerSHA256: "527ccf98054509311dde398c0ac8e8e75585eaec89d74639715de8e3d8f42b35",
	},
	"aarch64-unknown-linux-gnu": {
		archiveSHA256:         "f8d42e09036254091a5fc06c0476950b680335a726ca8ed0263ed87f7f884da4",
		mainSHA256:            "7b440882916f8b6857d0654db9dc92efbf6f2a7e373869b1e26d3056de4cf3d6",
		resourceScannerSHA256: "5f6560868fce1e9f1595e4d597bdb618a175c1b7b7799b474a9249bfcb3ec364",
	},
	"x86_64-unknown-linux-gnu": {
		archiveSHA256:         "fc09e2340de17279de63afb0b188f41cb181817518a4101738e17613eb12bc6d",
		mainSHA256:            "e1b2aab69cdeb41e0a4b2f259c31f2620356bb1765195c7f68739ede4df6fb2b",
		resourceScannerSHA256: "278357e511552ea7b9997ccb39341ece7036d8e0defa035a4ecb113566b864a0",
	},
}
