package cmd

import (
	"github.com/spf13/cobra"
)

var (
	guardrailsShowAPIKey string
	guardrailsShowModel  string
)

var guardrailsShowCmd = &cobra.Command{
	Use:   "show [file[:line]] [profile-dir]",
	Short: "Show the access-rules profile for a file or the whole repo",
	Long: `Show the access-rules profile generated by 'konvu guardrails scan'.

Reads .konvu/guardrails/ under the current directory unless a profile-dir is
given.

Thin wrapper over the cached guardrails-cli binary -- see 'konvu guardrails
scan --help' for the shared bootstrap/credentials behavior.`,
	Args: cobra.ArbitraryArgs,
	Run: func(cmd *cobra.Command, args []string) {
		runGuardrailsExec(append([]string{"show"}, args...), guardrailsShowAPIKey, guardrailsShowModel)
	},
}

func init() {
	guardrailsShowCmd.Flags().StringVar(&guardrailsShowAPIKey, "openai-api-key", "", "OpenAI API key; writes ~/.config/guardrails/credentials")
	guardrailsShowCmd.Flags().StringVar(&guardrailsShowModel, "openai-model", "gpt-4o", "OpenAI model, written alongside --openai-api-key")
	guardrailsCmd.AddCommand(guardrailsShowCmd)
}
